<Project>
  <PropertyGroup>
    <VersionPrefix Condition="'$(VersionPrefix)' == ''">0.8.0</VersionPrefix>
    <Version Condition="'$(Version)' == ''">$(VersionPrefix)</Version>
    <Authors>AiDataGateway</Authors>
    <Product>AiDataGateway</Product>
    <Copyright>Copyright © AiDataGateway</Copyright>
  </PropertyGroup>
</Project>
